[package]
name = "advent-2020"
version = "0.1.0"
authors = ["Robert Stratton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
peg = "0.6.3"
